# Generated by Django 6.0.6 on 2026-06-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Savatga qo'shilgan vaqt")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savatdagi maxsulot',
                'verbose_name_plural': 'Savatdagi maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug (URL uchun)')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimli maxsulot',
                'verbose_name_plural': "Sevimlilar ro'yxati",
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brend (Masalan: APPLE, NIKE)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narxi (so'mda)")),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Eski narxi (Chegirma uchun)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Asosiy rasm')),
                ('display_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Displey hajmi')),
                ('processor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Protsessor modeli')),
                ('internal_memory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ichki xotira')),
                ('camera', models.CharField(blank=True, max_length=150, null=True, verbose_name="Kamera o'lchamlari")),
                ('battery_info', models.CharField(blank=True, max_length=150, null=True, verbose_name='Batareya xususiyati')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rangi')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Trending Items qismiga chiqarish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='members.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Profil rasmi')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, null=True, verbose_name='Jinsi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.product', verbose_name="Sevimlilarga qo'shilgan mahsulot"),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
    ]
